/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.sedona.common.subDivide;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.KryoSerializable;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import java.io.Serializable;

/** Options for subdividing geometries */
public class SubdivideOptions implements KryoSerializable, Serializable {

  public enum MultiPointSubDivider {
    /** Decompose the MultiPoint into individual points */
    DECOMPOSE(1, true),

    /** Pack nearby points to avoid generating too many geometries */
    PACKING(2, true);

    public final int id;
    public final boolean isAccurate;

    MultiPointSubDivider(int id, boolean isAccurate) {
      this.id = id;
      this.isAccurate = isAccurate;
    }

    public static MultiPointSubDivider fromId(int id) {
      for (MultiPointSubDivider divider : MultiPointSubDivider.values()) {
        if (divider.id == id) {
          return divider;
        }
      }
      throw new IllegalArgumentException("Unknown MultiPointSubDivider id: " + id);
    }
  }

  public enum LineStringSubDivider {
    /**
     * Cut in the middle of segments. This may introduce numerical errors but this is negligible in
     * most cases, so this divider is marked as accurate.
     */
    CUT_SEGMENTS(1, true),

    /**
     * Preserve segments and only split at nodes. This may produce subdivided LineStrings slightly
     * larger than the restriction.
     */
    PRESERVE_SEGMENTS(2, true);

    public final int id;
    public final boolean isAccurate;

    LineStringSubDivider(int id, boolean isAccurate) {
      this.id = id;
      this.isAccurate = isAccurate;
    }

    public static LineStringSubDivider fromId(int id) {
      for (LineStringSubDivider divider : LineStringSubDivider.values()) {
        if (divider.id == id) {
          return divider;
        }
      }
      throw new IllegalArgumentException("Unknown LineStringSubDivider id: " + id);
    }
  }

  public enum PolygonSubDivider {
    /** Approximate the polygon with lots of boxes */
    BOX_APPROX(1, false),

    /** Subdivide using {@link GeometrySubDivider} */
    OVERLAY(2, true),

    /** Subdivide using {@link GeometrySubDivider} and enforce using JTS OverlayNG */
    OVERLAY_NG(3, true),

    /**
     * Subdivide by clipping geometries using boxes generated by {@link
     * PolygonSubDivider#BOX_APPROX}
     */
    OVERLAY_NG2(4, true),

    /** Subdivide by triangulation */
    TRIANGULATION(5, true);

    public final int id;
    public final boolean isAccurate;

    PolygonSubDivider(int id, boolean isAccurate) {
      this.id = id;
      this.isAccurate = isAccurate;
    }

    public static PolygonSubDivider fromId(int id) {
      for (PolygonSubDivider divider : PolygonSubDivider.values()) {
        if (divider.id == id) {
          return divider;
        }
      }
      throw new IllegalArgumentException("Unknown PolygonSubDivider id: " + id);
    }
  }

  public int maxCoordinates;
  public double maxWidth;
  public double maxHeight;
  public int maxDepth;
  public MultiPointSubDivider multiPointSubDivider;
  public LineStringSubDivider lineStringSubDivider;
  public PolygonSubDivider polygonSubDivider;

  public SubdivideOptions(double maxWidth, double maxHeight) {
    this(
        1000,
        maxWidth,
        maxHeight,
        50,
        MultiPointSubDivider.DECOMPOSE,
        LineStringSubDivider.CUT_SEGMENTS,
        PolygonSubDivider.BOX_APPROX);
  }

  public SubdivideOptions() {
    this(0.1, 0.1);
  }

  public SubdivideOptions(
      int maxCoordinates,
      double maxWidth,
      double maxHeight,
      int maxDepth,
      MultiPointSubDivider multiPointSubDivider,
      LineStringSubDivider lineStringSubDivider,
      PolygonSubDivider polygonSubDivider) {
    if (maxWidth <= 0 || maxHeight <= 0) {
      throw new IllegalArgumentException("Max width and height must be positive");
    }
    this.maxCoordinates = maxCoordinates;
    this.maxWidth = maxWidth;
    this.maxHeight = maxHeight;
    this.maxDepth = maxDepth;
    this.multiPointSubDivider = multiPointSubDivider;
    this.lineStringSubDivider = lineStringSubDivider;
    this.polygonSubDivider = polygonSubDivider;
  }

  @Override
  public void write(Kryo kryo, Output output) {
    output.writeInt(maxCoordinates);
    output.writeDouble(maxWidth);
    output.writeDouble(maxHeight);
    output.writeInt(maxDepth);
    output.writeInt(multiPointSubDivider.id);
    output.writeInt(lineStringSubDivider.id);
    output.writeInt(polygonSubDivider.id);
  }

  @Override
  public void read(Kryo kryo, Input input) {
    maxCoordinates = input.readInt();
    maxWidth = input.readDouble();
    maxHeight = input.readDouble();
    maxDepth = input.readInt();
    multiPointSubDivider = MultiPointSubDivider.fromId(input.readInt());
    lineStringSubDivider = LineStringSubDivider.fromId(input.readInt());
    polygonSubDivider = PolygonSubDivider.fromId(input.readInt());
  }
}
