# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

site_name: 'wherobots'

docs_dir: docs

plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: 'google'
            show_inheritance_diagram: True
            show_source: False
          paths: [../sedona/stats/]
theme:
  font:
    text: Space Grotesk
  name: 'material'
  logo: 'logo-symbol-no-background.png'
  palette:
    scheme: slate
    primary: 'black'
    accent: 'deep purple'
nav:
  - Code Reference: reference/
